#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$' | grep -v 'node_modules/')

if [ -n "$CHANGED_FILES" ]; then
  echo "🧹 Running ESLint on staged JS files..."
  npx eslint --fix $CHANGED_FILES
  git add $CHANGED_FILES
else
  echo "✅ No JS files to lint."
fi
