#!/bin/sh
set -e

echo "🔍 Husky pre-commit started"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$' | grep -v 'node_modules/' || true)

if [ -z "$CHANGED_FILES" ]; then
  echo "✅ No staged JS files to lint. Skipping ESLint."
  exit 0
fi

echo "🧹 Running ESLint on staged JS files:"
echo "$CHANGED_FILES"

npx eslint --fix $CHANGED_FILES || {
  echo "❌ ESLint failed"
  exit 1
}

git add $CHANGED_FILES

echo "✅ ESLint passed. Proceeding with commit."
